"use client";

import React from "react";
import {
  Document,
  Page,
  Text,
  View,
  Image,
  StyleSheet,
} from "@react-pdf/renderer";

type Territory = {
  stateId?: number | null;
  stateName?: string | null;
  gross?: number | null;
};

type OverseasCountry = {
  countryId?: number | null;
  countryName?: string | null;
  isoCode?: string | null;
  continent?: string | null;
  grossLocal?: number | null;
  grossUsd?: number | null;
  notes?: string | null;
};

type OfficialFigure = {
  id?: number | null;
  territory_name?: string | null;
  gross_official?: number | null;
  notes?: string | null;
};

export type ReportData = {
  movie: {
    id: number;
    title: string;
    originalTitle?: string | null;
    releaseYear?: number | null;
    releaseDate?: string | null;
    posterUrl?: string | null;
  };

  profile: {
    genre?: string | null;
    language?: string | null;

    industry?: {
      id?: number | null;
      name?: string | null;
      shortName?: string | null;
    } | null;

    director?: {
      name?: string | null;
    } | null;

    leadActor?: {
      name?: string | null;
      character?: string | null;
    } | null;

    leadActress?: {
      name?: string | null;
      character?: string | null;
    } | null;
  };

  boxOffice: {
    indiaGross?: number | null;
    overseasGross?: number | null;
    worldwideGross?: number | null;

    strongestIndianTerritory?: Territory | null;

    indianTerritories?: Territory[];

    overseasCountries?: OverseasCountry[];
  };

  overseas?: {
    totalGross?: number | null;
    countryWise?: OverseasCountry[];
  };

  officialFigures?: OfficialFigure[];

  business?: {
    productionBudgetTrade?: number | null;
    theatricalVerdict?: string | null;
  };

  /*
   * Automatically generated by the JMI API.
   *
   * This is currently rule-based and does not use
   * OpenAI or any external AI service.
   */
  performanceSummary?: string | null;
};

type JmiPerformanceReportPDFProps = {
  report: ReportData;
};

/*
 * ============================================================
 * JMI PDF STYLES
 * ============================================================
 */

const styles = StyleSheet.create({
  page: {
    backgroundColor: "#050505",
    color: "#F4F4F5",
    paddingTop: 58,
    paddingBottom: 52,
    paddingHorizontal: 42,
    fontFamily: "Helvetica",
  },

  /*
   * ----------------------------------------------------------
   * FIXED HEADER
   * ----------------------------------------------------------
   */

  header: {
    position: "absolute",
    top: 24,
    left: 42,
    right: 42,

    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",

    borderBottomWidth: 1,
    borderBottomColor: "#27272A",

    paddingBottom: 9,
  },

  brandBlock: {
    flexDirection: "row",
    alignItems: "center",
  },

  brandMark: {
    fontSize: 13,
    fontWeight: 700,
    color: "#FACC15",
    letterSpacing: 1.8,
  },

  brandDivider: {
    width: 1,
    height: 12,
    backgroundColor: "#3F3F46",
    marginHorizontal: 8,
  },

  brandSub: {
    fontSize: 6,
    color: "#71717A",
    letterSpacing: 1.2,
  },

  reportLabel: {
    fontSize: 6,
    color: "#A78BFA",
    letterSpacing: 1.2,
    textAlign: "right",
  },

  /*
   * ----------------------------------------------------------
   * FIXED FOOTER
   * ----------------------------------------------------------
   */

  footer: {
    position: "absolute",
    bottom: 22,
    left: 42,
    right: 42,

    flexDirection: "row",
    justifyContent: "space-between",

    borderTopWidth: 1,
    borderTopColor: "#18181B",

    paddingTop: 7,
  },

  footerText: {
    fontSize: 5.5,
    color: "#52525B",
  },

  pageNumber: {
    fontSize: 5.5,
    color: "#52525B",
  },

  /*
   * ----------------------------------------------------------
   * COVER
   * ----------------------------------------------------------
   */

  coverPage: {
    alignItems: "center",
    justifyContent: "center",
    paddingTop: 65,
    paddingBottom: 55,
  },

  coverEyebrow: {
    fontSize: 7,
    color: "#A78BFA",
    letterSpacing: 2.2,
    textAlign: "center",
    marginBottom: 9,
  },

  coverTitle: {
    fontSize: 28,
    fontWeight: 700,
    color: "#FFFFFF",
    lineHeight: 1.08,
    textAlign: "center",
    marginBottom: 8,
  },

  coverSubtitle: {
    fontSize: 8,
    color: "#71717A",
    letterSpacing: 1.2,
    textAlign: "center",
    marginBottom: 25,
  },

  posterFrame: {
    width: 205,
    height: 290,

    alignItems: "center",
    justifyContent: "center",

    backgroundColor: "#0D0D0F",

    borderWidth: 1,
    borderColor: "#3F3F46",

    padding: 5,

    marginBottom: 25,
  },

  poster: {
    width: 193,
    height: 278,
    objectFit: "contain",
  },

  posterPlaceholder: {
    width: 193,
    height: 278,
    alignItems: "center",
    justifyContent: "center",
  },

  posterPlaceholderText: {
    fontSize: 9,
    color: "#52525B",
    letterSpacing: 2,
  },

  coverMeta: {
    width: "100%",
    maxWidth: 430,

    flexDirection: "row",

    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: "#27272A",

    paddingVertical: 12,
  },

  coverMetaItem: {
    flex: 1,
    alignItems: "center",
  },

  coverMetaLabel: {
    fontSize: 5.5,
    color: "#71717A",
    letterSpacing: 1,
    textAlign: "center",
    marginBottom: 4,
  },

  coverMetaValue: {
    fontSize: 8,
    color: "#E4E4E7",
    textAlign: "center",
  },

  coverReleaseDate: {
    marginTop: 18,
    fontSize: 6.5,
    color: "#52525B",
    letterSpacing: 0.8,
    textAlign: "center",
  },

  /*
   * ----------------------------------------------------------
   * SECTIONS
   * ----------------------------------------------------------
   */

  section: {
    marginBottom: 22,
  },

  sectionEyebrow: {
    fontSize: 6,
    color: "#A78BFA",
    letterSpacing: 1.7,
    marginBottom: 4,
  },

  sectionTitle: {
    fontSize: 14,
    fontWeight: 700,
    color: "#FFFFFF",
    marginBottom: 9,
  },

  sectionRule: {
    height: 1,
    backgroundColor: "#27272A",
    marginBottom: 11,
  },

  /*
   * ----------------------------------------------------------
   * PROFILE
   * ----------------------------------------------------------
   */

  profileGrid: {
    flexDirection: "row",
    flexWrap: "wrap",

    borderTopWidth: 1,
    borderLeftWidth: 1,
    borderColor: "#27272A",
  },

  profileCell: {
    width: "50%",
    minHeight: 54,

    paddingVertical: 8,
    paddingHorizontal: 10,

    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderColor: "#27272A",
  },

  profileLabel: {
    fontSize: 5.5,
    color: "#71717A",
    textTransform: "uppercase",
    letterSpacing: 0.9,
    marginBottom: 4,
  },

  profileValue: {
    fontSize: 8,
    color: "#E4E4E7",
    lineHeight: 1.25,
  },

  /*
   * ----------------------------------------------------------
   * BOX OFFICE STAT CARDS
   * ----------------------------------------------------------
   */

  statsRow: {
    flexDirection: "row",
  },

  statCard: {
    flex: 1,

    minHeight: 68,

    padding: 10,

    backgroundColor: "#0C0C0E",

    borderWidth: 1,
    borderColor: "#27272A",

    marginRight: 6,
  },

  statCardLast: {
    marginRight: 0,
  },

  statLabel: {
    fontSize: 5.5,
    color: "#71717A",
    letterSpacing: 0.9,
    marginBottom: 7,
  },

  statValue: {
    fontSize: 12,
    fontWeight: 700,
    color: "#FACC15",
  },

  statValueSecondary: {
    fontSize: 12,
    fontWeight: 700,
    color: "#A78BFA",
  },

  /*
   * ----------------------------------------------------------
   * STRONGEST TERRITORY
   * ----------------------------------------------------------
   */

  strongestCard: {
    padding: 12,

    backgroundColor: "#0C0C0E",

    borderWidth: 1,
    borderColor: "#3F3F46",

    marginBottom: 11,
  },

  strongestTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },

  strongestLabel: {
    fontSize: 5.5,
    color: "#71717A",
    letterSpacing: 1,
    marginBottom: 4,
  },

  strongestName: {
    fontSize: 11,
    fontWeight: 700,
    color: "#FFFFFF",
  },

  strongestGross: {
    fontSize: 10,
    fontWeight: 700,
    color: "#FACC15",
  },

  /*
   * ----------------------------------------------------------
   * PROFESSIONAL TABLES
   * ----------------------------------------------------------
   */

  table: {
    width: "100%",
    borderWidth: 1,
    borderColor: "#27272A",
  },

  tableHeader: {
    flexDirection: "row",
    backgroundColor: "#17171A",
    minHeight: 25,
  },

  tableRow: {
    flexDirection: "row",
    minHeight: 24,
  },

  tableRowAlt: {
    backgroundColor: "#0A0A0C",
  },

  tableCell: {
    paddingVertical: 6,
    paddingHorizontal: 8,

    borderRightWidth: 1,
    borderBottomWidth: 1,

    borderColor: "#27272A",

    justifyContent: "center",
  },

  tableCellLast: {
    borderRightWidth: 0,
  },

  tableHeaderCell: {
    paddingVertical: 7,
    paddingHorizontal: 8,

    borderRightWidth: 1,
    borderBottomWidth: 1,

    borderColor: "#27272A",

    justifyContent: "center",
  },

  territoryName: {
    width: "64%",
  },

  territoryValue: {
    width: "36%",
    alignItems: "flex-end",
  },

  countryName: {
    width: "44%",
  },

  countryUsd: {
    width: "28%",
    alignItems: "flex-end",
  },

  countryLocal: {
    width: "28%",
    alignItems: "flex-end",
  },

  tableHeaderText: {
    fontSize: 5.5,
    color: "#A1A1AA",
    fontWeight: 700,
    letterSpacing: 0.8,
  },

  tableText: {
    fontSize: 7,
    color: "#D4D4D8",
  },

  tableNumber: {
    fontSize: 7,
    color: "#FACC15",
    textAlign: "right",
  },

  tableUsd: {
    fontSize: 7,
    color: "#A78BFA",
    textAlign: "right",
  },

  tableMuted: {
    fontSize: 7,
    color: "#A1A1AA",
    textAlign: "right",
  },

  /*
   * ----------------------------------------------------------
   * EMPTY STATE
   * ----------------------------------------------------------
   */

  emptyBox: {
    padding: 12,

    borderWidth: 1,
    borderColor: "#27272A",

    backgroundColor: "#0C0C0E",
  },

  emptyText: {
    fontSize: 7,
    color: "#71717A",
    lineHeight: 1.5,
  },

  /*
   * ----------------------------------------------------------
   * BUSINESS
   * ----------------------------------------------------------
   */

  businessGrid: {
    flexDirection: "row",
  },

  businessCard: {
    flex: 1,

    minHeight: 68,

    padding: 11,

    backgroundColor: "#0C0C0E",

    borderWidth: 1,
    borderColor: "#27272A",

    marginRight: 7,
  },

  businessCardLast: {
    marginRight: 0,
  },

  businessLabel: {
    fontSize: 5.5,
    color: "#71717A",
    letterSpacing: 0.8,
    marginBottom: 7,
  },

  businessValue: {
    fontSize: 10,
    fontWeight: 700,
    color: "#E4E4E7",
  },

  /*
   * ----------------------------------------------------------
   * OFFICIAL FIGURES
   * ----------------------------------------------------------
   */

  officialTable: {
    width: "100%",
    borderWidth: 1,
    borderColor: "#27272A",
  },

  officialHeader: {
    flexDirection: "row",
    backgroundColor: "#17171A",
  },

  officialRow: {
    flexDirection: "row",
    minHeight: 24,
  },

  officialTerritory: {
    width: "62%",
  },

  officialGross: {
    width: "38%",
    alignItems: "flex-end",
  },

  /*
   * ----------------------------------------------------------
   * PERFORMANCE SUMMARY
   * ----------------------------------------------------------
   */

  summaryCard: {
    padding: 14,

    backgroundColor: "#0C0C0E",

    borderWidth: 1,
    borderColor: "#3F3F46",

    borderLeftWidth: 3,
    borderLeftColor: "#A78BFA",
  },

  summaryTop: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },

  summaryDot: {
    width: 5,
    height: 5,

    backgroundColor: "#FACC15",

    marginRight: 7,
  },

  summaryLabel: {
    fontSize: 6,
    color: "#A78BFA",
    fontWeight: 700,
    letterSpacing: 1.2,
  },

  summaryText: {
    fontSize: 8,
    color: "#D4D4D8",
    lineHeight: 1.65,
  },

  /*
   * ----------------------------------------------------------
   * DATA NOTE
   * ----------------------------------------------------------
   */

  note: {
    padding: 11,

    backgroundColor: "#0A0A0C",

    borderWidth: 1,
    borderColor: "#27272A",

    borderLeftWidth: 2,
    borderLeftColor: "#A78BFA",
  },

  noteTitle: {
    fontSize: 6,
    color: "#A78BFA",
    fontWeight: 700,
    letterSpacing: 1,
    marginBottom: 5,
  },

  noteText: {
    fontSize: 6.5,
    color: "#71717A",
    lineHeight: 1.55,
  },

  /*
   * ----------------------------------------------------------
   * FINAL BRANDING
   * ----------------------------------------------------------
   */

  closingBrand: {
    marginTop: 8,
    paddingTop: 12,

    borderTopWidth: 1,
    borderTopColor: "#18181B",

    alignItems: "center",
  },

  closingBrandMain: {
    fontSize: 8,
    fontWeight: 700,
    color: "#FACC15",
    letterSpacing: 1.5,
  },

  closingBrandSub: {
    marginTop: 3,
    fontSize: 5.5,
    color: "#52525B",
    letterSpacing: 0.8,
  },
});

/*
 * ============================================================
 * FORMATTERS
 * ============================================================
 */

function formatCrore(
  value: number | null | undefined
): string {
  if (
    value === null ||
    value === undefined ||
    Number.isNaN(value)
  ) {
    return "Data not available";
  }

  const crore = value / 10000000;

  return `Rs. ${new Intl.NumberFormat(
    "en-IN",
    {
      maximumFractionDigits: 2,
    }
  ).format(crore)} Cr`;
}

function formatUsd(
  value: number | null | undefined
): string {
  if (
    value === null ||
    value === undefined ||
    Number.isNaN(value)
  ) {
    return "—";
  }

  return `$${new Intl.NumberFormat(
    "en-US",
    {
      maximumFractionDigits: 2,
    }
  ).format(value)}`;
}

function formatLocal(
  value: number | null | undefined
): string {
  if (
    value === null ||
    value === undefined ||
    Number.isNaN(value)
  ) {
    return "—";
  }

  return new Intl.NumberFormat(
    "en-IN",
    {
      maximumFractionDigits: 2,
    }
  ).format(value);
}

function formatReleaseDate(
  value: string | null | undefined
): string {
  if (!value) {
    return "Data not available";
  }

  const date = new Date(value);

  if (Number.isNaN(date.getTime())) {
    return value;
  }

  return date.toLocaleDateString(
    "en-IN",
    {
      day: "2-digit",
      month: "long",
      year: "numeric",
    }
  );
}

/*
 * ============================================================
 * DATA HELPERS
 * ============================================================
 */

function getCountryRows(
  report: ReportData
): OverseasCountry[] {
  if (
    report.boxOffice?.overseasCountries &&
    report.boxOffice.overseasCountries.length > 0
  ) {
    return report.boxOffice.overseasCountries;
  }

  if (
    report.overseas?.countryWise &&
    report.overseas.countryWise.length > 0
  ) {
    return report.overseas.countryWise;
  }

  return [];
}

function getOverseasTotal(
  report: ReportData
): number | null | undefined {
  if (
    report.boxOffice?.overseasGross !==
      null &&
    report.boxOffice?.overseasGross !==
      undefined
  ) {
    return report.boxOffice.overseasGross;
  }

  return report.overseas?.totalGross;
}

/*
 * ============================================================
 * PDF
 * ============================================================
 */

export default function JmiPerformanceReportPDF({
  report,
}: JmiPerformanceReportPDFProps) {
  const countryRows =
    getCountryRows(report);

  const overseasGross =
    getOverseasTotal(report);

  const movieTitle =
    report.movie.title ||
    "JMI Movie";

  const releaseYear =
    report.movie.releaseYear
      ? String(
          report.movie.releaseYear
        )
      : "—";

  const releaseDate =
    formatReleaseDate(
      report.movie.releaseDate
    );

  const industryName =
    report.profile.industry?.name ||
    "Data not available";

  const directorName =
    report.profile.director?.name ||
    "Data not available";

  const actorName =
    report.profile.leadActor?.name ||
    "Data not available";

  const actressName =
    report.profile.leadActress?.name ||
    "Data not available";

  const performanceSummary =
    report.performanceSummary ||
    "An automatic JMI performance summary could not be generated because sufficient report data was not available.";

  return (
    <Document
      title={`${movieTitle} - JMI Performance Analysis`}
      author="Jeruto Movie Intelligence"
      subject="JMI Movie Performance Analysis Report"
      creator="Jeruto Movie Intelligence"
    >
      {/* ===================================================== */}
      {/* COVER PAGE                                            */}
      {/* ===================================================== */}

      <Page
        size="A4"
        style={[
          styles.page,
          styles.coverPage,
        ]}
      >
        <View style={styles.header}>
          <View style={styles.brandBlock}>
            <Text style={styles.brandMark}>
              JMI
            </Text>

            <View
              style={styles.brandDivider}
            />

            <Text style={styles.brandSub}>
              JERUTO MOVIE INTELLIGENCE
            </Text>
          </View>

          <Text style={styles.reportLabel}>
            PERFORMANCE REPORT
          </Text>
        </View>

        <Text style={styles.coverEyebrow}>
          JMI MOVIE PERFORMANCE ANALYSIS
        </Text>

        <Text style={styles.coverTitle}>
          {movieTitle}
        </Text>

        <Text style={styles.coverSubtitle}>
          INDIAN FILM INDUSTRY DATA &amp;
          INTELLIGENCE
        </Text>

        {/* Centered poster */}
        <View style={styles.posterFrame}>
          {report.movie.posterUrl ? (
            <Image
              src={report.movie.posterUrl}
              style={styles.poster}
            />
          ) : (
            <View
              style={styles.posterPlaceholder}
            >
              <Text
                style={
                  styles.posterPlaceholderText
                }
              >
                JMI
              </Text>
            </View>
          )}
        </View>

        {/* Cover metadata */}
        <View style={styles.coverMeta}>
          <View style={styles.coverMetaItem}>
            <Text style={styles.coverMetaLabel}>
              RELEASE DATE
            </Text>

            <Text style={styles.coverMetaValue}>
              {releaseDate}
            </Text>
          </View>

          <View style={styles.coverMetaItem}>
            <Text style={styles.coverMetaLabel}>
              LANGUAGE
            </Text>

            <Text style={styles.coverMetaValue}>
              {report.profile.language ||
                "Data not available"}
            </Text>
          </View>

          <View style={styles.coverMetaItem}>
            <Text style={styles.coverMetaLabel}>
              INDUSTRY
            </Text>

            <Text style={styles.coverMetaValue}>
              {industryName}
            </Text>
          </View>
        </View>

        <Text style={styles.coverReleaseDate}>
          RELEASE YEAR · {releaseYear}
        </Text>

        <View
          style={styles.closingBrand}
        >
          <Text
            style={
              styles.closingBrandMain
            }
          >
            JMI
          </Text>

          <Text
            style={
              styles.closingBrandSub
            }
          >
            JERUTO MOVIE INTELLIGENCE
          </Text>
        </View>

        <View style={styles.footer}>
          <Text style={styles.footerText}>
            JMI · Jeruto Movie Intelligence
          </Text>

          <Text
            style={styles.pageNumber}
            render={({ pageNumber }) =>
              `Page ${pageNumber}`
            }
          />
        </View>
      </Page>

      {/* ===================================================== */}
      {/* MAIN REPORT — NATURAL FLOW                            */}
      {/* ===================================================== */}

      <Page
        size="A4"
        style={styles.page}
        wrap
      >
        <View
          style={styles.header}
          fixed
        >
          <View style={styles.brandBlock}>
            <Text style={styles.brandMark}>
              JMI
            </Text>

            <View
              style={styles.brandDivider}
            />

            <Text style={styles.brandSub}>
              JERUTO MOVIE INTELLIGENCE
            </Text>
          </View>

          <Text style={styles.reportLabel}>
            {movieTitle}
          </Text>
        </View>

        {/* =================================================== */}
        {/* 01 MOVIE PROFILE                                   */}
        {/* =================================================== */}

        <View style={styles.section}>
          <Text style={styles.sectionEyebrow}>
            01 · MOVIE PROFILE
          </Text>

          <Text style={styles.sectionTitle}>
            Movie Profile
          </Text>

          <View style={styles.sectionRule} />

          <View
            style={styles.profileGrid}
          >
            <View style={styles.profileCell}>
              <Text
                style={styles.profileLabel}
              >
                Title
              </Text>

              <Text
                style={styles.profileValue}
              >
                {movieTitle}
              </Text>
            </View>

            <View style={styles.profileCell}>
              <Text
                style={styles.profileLabel}
              >
                Release Date
              </Text>

              <Text
                style={styles.profileValue}
              >
                {releaseDate}
              </Text>
            </View>

            <View style={styles.profileCell}>
              <Text
                style={styles.profileLabel}
              >
                Genre
              </Text>

              <Text
                style={styles.profileValue}
              >
                {report.profile.genre ||
                  "Data not available"}
              </Text>
            </View>

            <View style={styles.profileCell}>
              <Text
                style={styles.profileLabel}
              >
                Language
              </Text>

              <Text
                style={styles.profileValue}
              >
                {report.profile.language ||
                  "Data not available"}
              </Text>
            </View>

            <View style={styles.profileCell}>
              <Text
                style={styles.profileLabel}
              >
                Industry
              </Text>

              <Text
                style={styles.profileValue}
              >
                {industryName}
              </Text>
            </View>

            <View style={styles.profileCell}>
              <Text
                style={styles.profileLabel}
              >
                Director
              </Text>

              <Text
                style={styles.profileValue}
              >
                {directorName}
              </Text>
            </View>

            <View style={styles.profileCell}>
              <Text
                style={styles.profileLabel}
              >
                Lead Actor
              </Text>

              <Text
                style={styles.profileValue}
              >
                {actorName}
              </Text>
            </View>

            <View style={styles.profileCell}>
              <Text
                style={styles.profileLabel}
              >
                Lead Actress
              </Text>

              <Text
                style={styles.profileValue}
              >
                {actressName}
              </Text>
            </View>
          </View>
        </View>

        {/* =================================================== */}
        {/* 02 BOX OFFICE                                      */}
        {/* =================================================== */}

        <View style={styles.section}>
          <Text style={styles.sectionEyebrow}>
            02 · BOX OFFICE PERFORMANCE
          </Text>

          <Text style={styles.sectionTitle}>
            Worldwide Performance
          </Text>

          <View style={styles.sectionRule} />

          <View style={styles.statsRow}>
            <View style={styles.statCard}>
              <Text style={styles.statLabel}>
                INDIA
              </Text>

              <Text style={styles.statValue}>
                {formatCrore(
                  report.boxOffice
                    .indiaGross
                )}
              </Text>
            </View>

            <View style={styles.statCard}>
              <Text style={styles.statLabel}>
                OVERSEAS
              </Text>

              <Text
                style={
                  styles.statValueSecondary
                }
              >
                {formatCrore(
                  overseasGross
                )}
              </Text>
            </View>

            <View
              style={[
                styles.statCard,
                styles.statCardLast,
              ]}
            >
              <Text style={styles.statLabel}>
                WORLDWIDE
              </Text>

              <Text style={styles.statValue}>
                {formatCrore(
                  report.boxOffice
                    .worldwideGross
                )}
              </Text>
            </View>
          </View>
        </View>

        {/* =================================================== */}
        {/* 03 INDIA                                           */}
        {/* =================================================== */}

        <View style={styles.section}>
          <Text style={styles.sectionEyebrow}>
            03 · INDIAN MARKET PERFORMANCE
          </Text>

          <Text style={styles.sectionTitle}>
            Indian Territory Performance
          </Text>

          <View style={styles.sectionRule} />

          {report.boxOffice
            .strongestIndianTerritory ? (
            <View
              style={styles.strongestCard}
            >
              <View
                style={styles.strongestTop}
              >
                <View>
                  <Text
                    style={
                      styles.strongestLabel
                    }
                  >
                    STRONGEST PERFORMING
                    TERRITORY
                  </Text>

                  <Text
                    style={
                      styles.strongestName
                    }
                  >
                    {
                      report.boxOffice
                        .strongestIndianTerritory
                        .stateName
                    }
                  </Text>
                </View>

                <Text
                  style={
                    styles.strongestGross
                  }
                >
                  {formatCrore(
                    report.boxOffice
                      .strongestIndianTerritory
                      .gross
                  )}
                </Text>
              </View>
            </View>
          ) : (
            <View
              style={styles.emptyBox}
            >
              <Text
                style={styles.emptyText}
              >
                Indian territory data not
                available.
              </Text>
            </View>
          )}

          {report.boxOffice
            .indianTerritories &&
          report.boxOffice
            .indianTerritories.length >
            0 ? (
            <View
              style={styles.table}
            >
              <View
                style={styles.tableHeader}
              >
                <View
                  style={[
                    styles.tableHeaderCell,
                    styles.territoryName,
                  ]}
                >
                  <Text
                    style={
                      styles.tableHeaderText
                    }
                  >
                    TERRITORY
                  </Text>
                </View>

                <View
                  style={[
                    styles.tableHeaderCell,
                    styles.territoryValue,
                    styles.tableCellLast,
                  ]}
                >
                  <Text
                    style={
                      styles.tableHeaderText
                    }
                  >
                    JMI GROSS
                  </Text>
                </View>
              </View>

              {report.boxOffice.indianTerritories.map(
                (
                  territory,
                  index
                ) => (
                  <View
                    wrap={false}
                    style={[
                      styles.tableRow,
                      index % 2 === 1
                        ? styles.tableRowAlt
                        : {},
                    ]}
                    key={`${territory.stateId ?? "state"}-${index}`}
                  >
                    <View
                      style={[
                        styles.tableCell,
                        styles.territoryName,
                      ]}
                    >
                      <Text
                        style={
                          styles.tableText
                        }
                      >
                        {territory.stateName ||
                          "Unknown Territory"}
                      </Text>
                    </View>

                    <View
                      style={[
                        styles.tableCell,
                        styles.territoryValue,
                        styles.tableCellLast,
                      ]}
                    >
                      <Text
                        style={
                          styles.tableNumber
                        }
                      >
                        {formatCrore(
                          territory.gross
                        )}
                      </Text>
                    </View>
                  </View>
                )
              )}
            </View>
          ) : (
            <View
              style={styles.emptyBox}
            >
              <Text
                style={styles.emptyText}
              >
                Indian territory data not
                available.
              </Text>
            </View>
          )}
        </View>

        {/* =================================================== */}
        {/* 04 OVERSEAS                                        */}
        {/* =================================================== */}

        <View style={styles.section}>
          <Text style={styles.sectionEyebrow}>
            04 · OVERSEAS PERFORMANCE
          </Text>

          <Text style={styles.sectionTitle}>
            Overseas Country-wise Performance
          </Text>

          <View style={styles.sectionRule} />

          {countryRows.length > 0 ? (
            <View
              style={styles.table}
            >
              <View
                style={styles.tableHeader}
              >
                <View
                  style={[
                    styles.tableHeaderCell,
                    styles.countryName,
                  ]}
                >
                  <Text
                    style={
                      styles.tableHeaderText
                    }
                  >
                    COUNTRY
                  </Text>
                </View>

                <View
                  style={[
                    styles.tableHeaderCell,
                    styles.countryUsd,
                  ]}
                >
                  <Text
                    style={
                      styles.tableHeaderText
                    }
                  >
                    GROSS USD
                  </Text>
                </View>

                <View
                  style={[
                    styles.tableHeaderCell,
                    styles.countryLocal,
                    styles.tableCellLast,
                  ]}
                >
                  <Text
                    style={
                      styles.tableHeaderText
                    }
                  >
                    LOCAL GROSS
                  </Text>
                </View>
              </View>

              {countryRows.map(
                (
                  country,
                  index
                ) => (
                  <View
                    wrap={false}
                    style={[
                      styles.tableRow,
                      index % 2 === 1
                        ? styles.tableRowAlt
                        : {},
                    ]}
                    key={`${country.countryId ?? "country"}-${index}`}
                  >
                    <View
                      style={[
                        styles.tableCell,
                        styles.countryName,
                      ]}
                    >
                      <Text
                        style={
                          styles.tableText
                        }
                      >
                        {country.countryName ||
                          "Unknown Country"}
                      </Text>
                    </View>

                    <View
                      style={[
                        styles.tableCell,
                        styles.countryUsd,
                      ]}
                    >
                      <Text
                        style={
                          styles.tableUsd
                        }
                      >
                        {formatUsd(
                          country.grossUsd
                        )}
                      </Text>
                    </View>

                    <View
                      style={[
                        styles.tableCell,
                        styles.countryLocal,
                        styles.tableCellLast,
                      ]}
                    >
                      <Text
                        style={
                          styles.tableMuted
                        }
                      >
                        {formatLocal(
                          country.grossLocal
                        )}
                      </Text>
                    </View>
                  </View>
                )
              )}
            </View>
          ) : (
            <View
              style={styles.emptyBox}
            >
              <Text
                style={styles.emptyText}
              >
                Overseas country-wise data not
                available.
              </Text>
            </View>
          )}
        </View>

        {/* =================================================== */}
        {/* 05 OFFICIAL FIGURES                                */}
        {/* =================================================== */}

        <View style={styles.section}>
          <Text style={styles.sectionEyebrow}>
            05 · OFFICIAL FIGURES
          </Text>

          <Text style={styles.sectionTitle}>
            Official Production House Figures
          </Text>

          <View style={styles.sectionRule} />

          {report.officialFigures &&
          report.officialFigures.length >
            0 ? (
            <View
              style={styles.officialTable}
            >
              <View
                style={styles.officialHeader}
              >
                <View
                  style={[
                    styles.tableHeaderCell,
                    styles.officialTerritory,
                  ]}
                >
                  <Text
                    style={
                      styles.tableHeaderText
                    }
                  >
                    TERRITORY
                  </Text>
                </View>

                <View
                  style={[
                    styles.tableHeaderCell,
                    styles.officialGross,
                    styles.tableCellLast,
                  ]}
                >
                  <Text
                    style={
                      styles.tableHeaderText
                    }
                  >
                    OFFICIAL GROSS
                  </Text>
                </View>
              </View>

              {report.officialFigures.map(
                (
                  figure,
                  index
                ) => (
                  <View
                    wrap={false}
                    style={[
                      styles.officialRow,
                      index % 2 === 1
                        ? styles.tableRowAlt
                        : {},
                    ]}
                    key={`${figure.id ?? "official"}-${index}`}
                  >
                    <View
                      style={[
                        styles.tableCell,
                        styles.officialTerritory,
                      ]}
                    >
                      <Text
                        style={
                          styles.tableText
                        }
                      >
                        {figure.territory_name ||
                          "Official Figure"}
                      </Text>
                    </View>

                    <View
                      style={[
                        styles.tableCell,
                        styles.officialGross,
                        styles.tableCellLast,
                      ]}
                    >
                      <Text
                        style={
                          styles.tableNumber
                        }
                      >
                        {formatCrore(
                          figure.gross_official
                        )}
                      </Text>
                    </View>
                  </View>
                )
              )}
            </View>
          ) : (
            <View
              style={styles.emptyBox}
            >
              <Text
                style={styles.emptyText}
              >
                Official production house figures
                not available.
              </Text>
            </View>
          )}
        </View>

        {/* =================================================== */}
        {/* 06 BUSINESS                                        */}
        {/* =================================================== */}

        <View style={styles.section}>
          <Text style={styles.sectionEyebrow}>
            06 · BUSINESS OVERVIEW
          </Text>

          <Text style={styles.sectionTitle}>
            Theatrical Business
          </Text>

          <View style={styles.sectionRule} />

          <View
            style={styles.businessGrid}
          >
            <View
              style={styles.businessCard}
            >
              <Text
                style={styles.businessLabel}
              >
                ESTIMATED TRADE BUDGET
              </Text>

              <Text
                style={styles.businessValue}
              >
                {formatCrore(
                  report.business
                    ?.productionBudgetTrade
                )}
              </Text>
            </View>

            <View
              style={[
                styles.businessCard,
                styles.businessCardLast,
              ]}
            >
              <Text
                style={styles.businessLabel}
              >
                THEATRICAL VERDICT
              </Text>

              <Text
                style={styles.businessValue}
              >
                {report.business
                  ?.theatricalVerdict ||
                  "Data not available"}
              </Text>
            </View>
          </View>
        </View>

        {/* =================================================== */}
        {/* 07 PERFORMANCE SUMMARY                              */}
        {/* =================================================== */}

        <View style={styles.section}>
          <Text style={styles.sectionEyebrow}>
            07 · JMI PERFORMANCE SUMMARY
          </Text>

          <Text style={styles.sectionTitle}>
            Overall Performance
          </Text>

          <View style={styles.sectionRule} />

          <View
            style={styles.summaryCard}
          >
            <View
              style={styles.summaryTop}
            >
              <View
                style={styles.summaryDot}
              />

              <Text
                style={styles.summaryLabel}
              >
                JMI AUTOMATED ANALYSIS
              </Text>
            </View>

            <Text
              style={styles.summaryText}
            >
              {performanceSummary}
            </Text>
          </View>
        </View>

        {/* =================================================== */}
        {/* DATA NOTE                                           */}
        {/* =================================================== */}

        <View style={styles.section}>
          <View style={styles.note}>
            <Text style={styles.noteTitle}>
              JMI DATA NOTE
            </Text>

            <Text style={styles.noteText}>
              This report is generated from data
              tracked and maintained by Jeruto
              Movie Intelligence. Collection
              figures may include JMI trade
              estimates where official figures are
              unavailable. Official figures are
              presented separately where available.
              Country-wise overseas figures are
              shown as a separate market breakdown
              and are not added again to the
              aggregate overseas total.
            </Text>
          </View>
        </View>

        <View
          style={styles.closingBrand}
        >
          <Text
            style={styles.closingBrandMain}
          >
            JMI · JERUTO MOVIE INTELLIGENCE
          </Text>

          <Text
            style={styles.closingBrandSub}
          >
            INDIAN FILM INDUSTRY DATA &amp;
            INTELLIGENCE
          </Text>
        </View>

        <View
          style={styles.footer}
          fixed
        >
          <Text style={styles.footerText}>
            JMI · Jeruto Movie Intelligence
          </Text>

          <Text
            style={styles.pageNumber}
            render={({ pageNumber }) =>
              `Page ${pageNumber}`
            }
          />
        </View>
      </Page>
    </Document>
  );
}